name: flutter_ume_kit_console_animenzzz
description: Show debugPrint kit for flutter_ume.
version: 1.1.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  flutter_ume_animenzzz: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
